### ISSUE TITLE
[Icon Request]: 

### ISSUE THREAD

**Issue by wraith1385** [walkxhub/dashboard-icons#101]
**What is the name of the icon(s)?**
ErsatzTV

**What is the website/page of the icon(s)?**
https://ersatztv.org/

**Upload the icon(s) here: [Optional]**
![ersatztv-square-logo](https://user-images.githubusercontent.com/1617434/169714973-6b0d230f-80d7-4cf6-bbee-4c6877ec0a72.png)

**Comment by walkxcode** [comment]
Hey,
Thanks for suggesting an icon! Your icon(s) have been added to the repo. 🤍
