### ISSUE TITLE
[Icon Request]: 

### ISSUE THREAD

**Issue by wraith1385** [walkxhub/dashboard-icons#102]
**What is the name of the icon(s)?**
oVirt

**What is the website/page of the icon(s)?**
https://www.ovirt.org/

**Upload the icon(s) here: [Optional]**
![ovirt](https://user-images.githubusercontent.com/1617434/169715014-d9827d32-41c4-4951-b6ca-ed0283213abc.svg)

**Comment by walkxcode** [comment]
Do you have a square version of this icon?

**Comment by wraith1385** [comment]
How about this
![ovirt](https://user-images.githubusercontent.com/1617434/169715192-43410baa-e430-4bbf-9653-12dc80d35d71.png)
?

**Comment by walkxcode** [comment]
Hey,
Thanks for suggesting an icon! Your icon(s) have been added to the repo. 🤍
