### ISSUE TITLE
[Icon Request]: RSS-Bridge

### ISSUE THREAD

**Issue by agrider** [walkxhub/dashboard-icons#103]
**What is the name of the icon(s)?**
RSS-Bridge

**What is the website/page of the icon(s)?**
https://github.com/rss-bridge/rss-bridge

**Upload the icon(s) here: [Optional]**
https://raw.githubusercontent.com/RSS-Bridge/rss-bridge/master/static/favicon.png

**Comment by walkxcode** [comment]
That image seems to be very small, do you have a bigger one?

**Comment by agrider** [comment]
Sorry, I don't. They do have [the svg that the favicon is generated from](https://github.com/RSS-Bridge/rss-bridge/tree/master/static/favicon.svg) in the same folder but it doesn't include the text. I'm afraid I'm a dolt when it comes to that type of thing or I'd make up a larger image.

**Comment by walkxcode** [comment]
I've found an image of respectable size online. Will add to the repo now.

**Comment by walkxcode** [comment]
Hey,
Thanks for suggesting an icon! Your icon(s) have been added to the repo. 🤍
