### ISSUE TITLE
[Icon Request]: Kasm Workspaces

### ISSUE THREAD

**Issue by sylar6725** [walkxhub/dashboard-icons#106]
**What is the name of the icon(s)?**
Kasm Workspaces

**What is the website/page of the icon(s)?**
(https://www.kasmweb.com)

**Upload the icon(s) here: [Optional]**
![kasm](https://user-images.githubusercontent.com/71662117/170772566-b266d31c-2baf-4b4b-9906-0f392e52c81c.png)

**Comment by walkxcode** [comment]
Hey,
Thanks for suggesting an icon! Your icon(s) have been added to the repo. 🤍
