### ISSUE TITLE
[Icon Request]: OpenSearch

### ISSUE THREAD

**Issue by Just5KY** [walkxhub/dashboard-icons#108]
**What is the name of the icon(s)?**
[OpenSearch]

**What is the website/page of the icon(s)?**
[https://opensearch.org/] [https://github.com/opensearch-project]

**Upload the icon(s) here: [Optional]**
Upload the icon, MUST be `PNG` or `SVG`.

![image](https://user-images.githubusercontent.com/71321862/170898910-a842dfc4-09bf-4b6d-9094-3120f3b4f637.png)

![](https://opensearch.org/assets/img/apple-touch-icon.png)

**Comment by walkxcode** [comment]
Hey,
Thanks for suggesting an icon! Your icon(s) have been added to the repo. 🤍
