### ISSUE TITLE
[Icon Request]: Unifi Protect

### ISSUE THREAD

**Issue by austempest** [walkxhub/dashboard-icons#111]
**What is the name of the icon(s)?**
Unifi Protect

**What is the website/page of the icon(s)?**
https://www.ui.com/download-software/

**Upload the icon(s) here: [Optional]**
Upload the icon, MUST be `PNG` or `SVG`.
![unifi-protect](https://user-images.githubusercontent.com/22319559/172035174-72a4bff1-15e7-46de-9b94-d6e84a9681d6.png)

**Comment by walkxcode** [comment]
Hey,
Thanks for suggesting an icon! Your icon(s) have been added to the repo. 🤍
