### ISSUE TITLE
[Icon Request]: Hyperion Project

### ISSUE THREAD

**Issue by psychowood** [walkxhub/dashboard-icons#120]
**What is the name of the icon(s)?**
Hyperion Project

**What is the website/page of the icon(s)?**
[Github repo](https://github.com/hyperion-project/hyperion.ng/)

[icon source](https://github.com/hyperion-project/hyperion.ng/blob/master/resources/icons/hyperion-icon-512px.png)

**Upload the icon(s) here: [Optional]**
![hyperion-icon-512px](https://user-images.githubusercontent.com/115389/173415217-8f1c4be6-5052-4a31-b669-251a83a54433.png)

Thanks!

**Comment by walkxcode** [comment]
Hey,
Thanks for suggesting an icon! Your icon(s) have been added to the repo. 🤍
