### ISSUE TITLE
[Icon Request]: 

### ISSUE THREAD

**Issue by StarFleetCPTN** [walkxhub/dashboard-icons#122]
**What is the name of the icon(s)?**
Omada Software Controller

**What is the website/page of the icon(s)?**
https://www.tp-link.com/us/business-networking/omada-sdn-controller/omada-software-controller/

**Upload the icon(s) here: [Optional]**
![omada](https://user-images.githubusercontent.com/2897199/173869166-d5cd591e-f41c-4b16-aded-a228bdac7b12.svg)

**Comment by walkxcode** [comment]
Hey,
Thanks for suggesting an icon! Your icon(s) have been added to the repo. 🤍
