### ISSUE TITLE
[Icon Request]: Xen Orchestra Appliance

### ISSUE THREAD

**Issue by Dubwize** [walkxhub/dashboard-icons#123]
**What is the name of the icon(s)?**
XOA or Xen Orchestra Appliance 

**What is the website/page of the icon(s)?**
https://xen-orchestra.com/

**Upload the icon(s) here: [Optional]**
![xo-logo](https://user-images.githubusercontent.com/16105140/174279347-0bf10b2f-f222-4266-a760-404ed83bc719.png)

**Comment by walkxcode** [comment]
Hey,
Thanks for suggesting an icon! Your icon(s) have been added to the repo. 🤍
