### ISSUE TITLE
[Icon Request]: Shelly

### ISSUE THREAD

**Issue by mschulze46** [walkxhub/dashboard-icons#124]
**What is the name of the icon(s)?**
Shelly

**What is the website/page of the icon(s)?**
[https://shelly.cloud/](https://shelly.cloud/)

**Upload the icon(s) here: [Optional]**
![shelly_logo_white_200x80](https://user-images.githubusercontent.com/30439703/174328930-8ce484bd-5231-459d-9e30-0c684408b6af.png)

**Comment by walkxcode** [comment]
Hey,
Thanks for suggesting an icon! Your icon(s) have been added to the repo. 🤍

**Comment by mschulze46** [comment]
You are freakin' awesome! Thanks!
