### ISSUE TITLE
[Icon Request]: HomeSeer

### ISSUE THREAD

**Issue by MistarMuffin** [walkxhub/dashboard-icons#128]
**What is the name of the icon(s)?**
HomeSeer

**What is the website/page of the icon(s)?**
[[Eg. https://portainer.io]](https://homeseer.com/)

**Upload the icon(s) here: [Optional]**
Upload the icon, MUST be `PNG` or `SVG`.

**Comment by walkxcode** [comment]
Hey,
Thanks for suggesting an icon! Your icon(s) have been added to the repo. 🤍
