### ISSUE TITLE
[Icon Request]: Checkmk

### ISSUE THREAD

**Issue by Dubwize** [walkxhub/dashboard-icons#131]
**What is the name of the icon(s)?**
Check MK

**What is the website/page of the icon(s)?**
www.checkmk.com

**Upload the icon(s) here: [Optional]**
![mk-logo](https://user-images.githubusercontent.com/16105140/174801711-fba488d3-c19f-4cf7-a145-ec4a073cb05c.svg)

There is a checkmk icon.  but it's either for something else, or an old icon.
for reference: https://cdn.jsdelivr.net/gh/walkxhub/dashboard-icons@master/png/checkmk.png

**Comment by Dubwize** [comment]
Hmm didn't realize there was the text there.  I'll try and find a better one.

**Comment by Dubwize** [comment]
![checkmk_logo_neg_v1](https://user-images.githubusercontent.com/16105140/174803148-99e3dc10-fb8f-4f66-8e26-7bbff2719d98.svg)
![checkmk_logo_neg_v2](https://user-images.githubusercontent.com/16105140/174803160-e2b02ff5-6d56-4a49-a4ec-589ef8f852cf.svg)

Wondering If either of these will do?

**Comment by Dubwize** [comment]
![checkmk_icon_main](https://user-images.githubusercontent.com/16105140/174803400-e1a2c892-2a37-4a47-b91c-c14e6388ab57.png)
![checkmk_icon_neg_v1](https://user-images.githubusercontent.com/16105140/174803405-9c072d38-e3b2-4a8d-9779-73603838f55e.png)
![checkmk_icon_neg_v2](https://user-images.githubusercontent.com/16105140/174803406-b23f1fd8-bbc9-4014-92eb-9aaddb874b5e.png)

Will any of these work for you?

**Comment by walkxcode** [comment]
Hey,
Thanks for suggesting an icon! Your icon(s) have been added to the repo. 🤍
