### ISSUE TITLE
[Icon Request]: ASUS Router

### ISSUE THREAD

**Issue by deffcolony** [walkxhub/dashboard-icons#148]
**What is the name of the icon(s)?**
asusrouter

**What is the website/page of the icon(s)?**
- https://www.asus.com/Content/ASUS-Router-App/

**Upload the icon(s) here: [Optional]**
![Amazing Idea](https://i.imgur.com/uqABCFA.png)

**Comment by walkxcode** [comment]
Hey, sorry for the delayed response, I was on vacation. Your icon has been added in the latest commit!
