### ISSUE TITLE
[Icon Request]: Koillection

### ISSUE THREAD

**Issue by ghost-of-cerberus** [walkxhub/dashboard-icons#149]
**What is the name of the icon(s)?**
Koillection

**What is the website/page of the icon(s)?**
https://github.com/koillection/koillection

**Upload the icon(s) here: [Optional]**
![koillection_round](https://user-images.githubusercontent.com/72414011/179403493-fcfa4eb5-0479-4042-8c74-9f8356f03fc2.png)

**Comment by walkxcode** [comment]
Hey, sorry for the delayed response, I was on vacation. Your icon has been added in the latest commit!
