### ISSUE TITLE
[Icon Request]: Castopod

### ISSUE THREAD

**Issue by MayhemBill** [walkxhub/dashboard-icons#150]
**What is the name of the icon(s)?**
[Eg. Portainer]
Castopod
**What is the website/page of the icon(s)?**
[Eg. https://portainer.io]
https://castopod.org
**Upload the icon(s) here: [Optional]**
Upload the icon, MUST be `PNG` or `SVG`.

**Comment by walkxcode** [comment]
Hey, sorry for the delayed response, I was on vacation. Your icon has been added in the latest commit!
