### ISSUE TITLE
[Icon Request]: Oracle Cloud

### ISSUE THREAD

**Issue by N4v41** [walkxhub/dashboard-icons#152]
**What is the name of the icon(s)?**
oci

**What is the website/page of the icon(s)?**
(https://www.oracle.com/cloud/)

**Upload the icon(s) here: [Optional]**
Upload the icon, MUST be `PNG` or `SVG`.
![oci](https://user-images.githubusercontent.com/45365461/180609878-f9f41b08-044e-4da4-b391-70e38206a82c.svg)

**Comment by walkxcode** [comment]
Hey, sorry for the delayed response, I was on vacation. Your icon has been added in the latest commit!
