### ISSUE TITLE
[Icon Request]: Nextcloud svg

### ISSUE THREAD

**Issue by xf-** [walkxhub/dashboard-icons#153]
**What is the name of the icon(s)?**
nextcloud

**What is the website/page of the icon(s)?**
You have already a PNG version

**Comment by nicolasluckie** [comment]
Added in #155

**Comment by xf-** [comment]
Nice, there a lot more icons I noticed, and I know there is an SVG out there.

At the moment I use ameixa icons. I have them on Android and the look is more unified :)
