### ISSUE TITLE
[Icon Request]: SearXNG

### ISSUE THREAD

**Issue by UbioZur** [walkxhub/dashboard-icons#157]
**What is the name of the icon(s)?**
SearXNG

**What is the website/page of the icon(s)?**
(https://docs.searxng.org/)

**Upload the icon(s) here: [Optional]**
![searxng](https://user-images.githubusercontent.com/13650202/182093302-83479681-018e-43f7-b54e-e3f805990851.svg)

**Comment by walkxcode** [comment]
Hey, sorry for the delayed response, I was on vacation. Your icon has been added in the latest commit!
