### ISSUE TITLE
All Icons are Broken!

### ISSUE THREAD

**Issue by Avotrix** [walkxhub/dashboard-icons#158]
We noticed that all icons are broken!! any idea why?

**Comment by deffcolony** [comment]
Hey @Avotrix, 

Could you be more specific by answering my following questions?

**What is the Environment you are trying to insert the icons in?**


**Do you have steps to reproduce the Bug?**


**What is Expected Result?**


**What is the Actual Result?** (yes you said the icons are broken but here comes the next question:)


**Do you have any Visual Proof (screenshots, videos, text) of the Bug**


**Does it have high Priority?**

**Comment by walkxcode** [comment]
> We noticed that all icons are broken!! any idea why?

Hey, sorry for the delayed response, I was on vacation.

Like @deffcolony mentioned, could you be more specific? All icons are working perfectly fine on my end.

**Comment by Avotrix** [comment]
no problem walkxcode the problem got resolved, I guess that was a domain issue, and the next day the site became reachable and the icons did show-up!

**Comment by walkxcode** [comment]
Alright! Closing this as completed.
