### ISSUE TITLE
[Icon Request]: 

### ISSUE THREAD

**Issue by rkretzschmann** [walkxhub/dashboard-icons#161]
**What is the name of the icon(s)?**
Fritzbox

**What is the website/page of the icon(s)?**
https://avm.de/produkte/fritzbox/

**Upload the icon(s) here: [Optional]**
![fritzbox](https://user-images.githubusercontent.com/53186662/183220140-59bf6cb6-aca5-418f-a799-f62d642cc8d0.svg)

**Comment by deffcolony** [comment]
@rkretzschmann That icon is already added: 
[https://github.com/walkxhub/dashboard-icons/blob/master/png/avmfritzbox.png](https://github.com/walkxhub/dashboard-icons/blob/master/png/avmfritzbox.png)
