### ISSUE TITLE
[Icon Request]: rathole

### ISSUE THREAD

**Issue by imlonghao** [walkxhub/dashboard-icons#166]
**What is the name of the icon(s)?**

rathole

**What is the website/page of the icon(s)?**

https://github.com/rapiz1/rathole

**Upload the icon(s) here: [Optional]**

https://github.com/rapiz1/rathole/raw/main/docs/img/rathole-logo.png

or

https://avatars.githubusercontent.com/u/97967683 ( source https://github.com/rathole-org )

**Comment by walkxcode** [comment]
Hey, thanks for your request. Would you happen to have a transparent version of this logo? Thanks in advance.

**Comment by deffcolony** [comment]
@walkxcode i made the logo transparent. Is this good?:

  ![image](https://i.imgur.com/gHiNpSe.png)
