### ISSUE TITLE
[Enhancement]: Whoogle image

### ISSUE THREAD

**Issue by Just5KY** [walkxhub/dashboard-icons#49]
**What do you want to enhance?**
Whoogle

**What is the enhancement?**
Google colors

**Additional info**
[Reddit Post](https://www.reddit.com/r/selfhosted/comments/sw4rtb/just_created_a_new_logo_for_whoogle/)

Credits to [u/Mother_Construction2](https://www.reddit.com/user/Mother_Construction2/)

**Comment by walkxcode** [comment]
Hello, unfortunately, this is not the official whoogle logo.
