### ISSUE TITLE
[Icon Request]: PiKVM

### ISSUE THREAD

**Issue by tmeuze** [walkxhub/dashboard-icons#50]
**What is the name of the icon(s)?**
PiKVM

**What is the website/page of the icon(s)?**
[pikvm.org](https://pikvm.org/)

**Upload the icon(s) here: [Optional]**
Upload the icon, MUST be `PNG` or `SVG`.
![pikvm](https://user-images.githubusercontent.com/9298659/155047021-a54658d9-62dd-4bc9-8812-e9c8611a24b0.png)

Thanks a lot!

**Comment by walkxcode** [comment]
Thank you, the icon has been added!
