### ISSUE TITLE
[Icon Request]: Authentik

### ISSUE THREAD

**Issue by tmeuze** [walkxhub/dashboard-icons#51]
**What is the name of the icon(s)?**
Authentik

**What is the website/page of the icon(s)?**
[goauthentik.io](https://goauthentik.io)

**Upload the icon(s) here: [Optional]**
 ![icon_left_brand](https://user-images.githubusercontent.com/9298659/155052798-0f627c5e-ed93-4f70-a3d2-6d1740193a29.svg)

**Comment by walkxcode** [comment]
Thank you!

**Comment by tmeuze** [comment]
You rock, thank you!
