### ISSUE TITLE
[Icon Request]: sschwifty, ddns-updater, high res lidarr

### ISSUE THREAD

**Issue by hugalafutro** [walkxhub/dashboard-icons#52]
**What is the name of the icon(s)?**
sschwifty.png
ddns-updater.png
lidarr.png (higher resolution than the current one)

**What is the website/page of the icon(s)?**
https://github.com/nirui/sshwifty/blob/master/ui/sshwifty.svg
https://raw.githubusercontent.com/qdm12/ddns-updater/2bede070de1357049891c2d9a5bf4f8aeadd5301/internal/server/ui/favicon.ico
https://github.com/walkxhub/dashboard-icons/blob/master/png/lidarr.png

**Upload the icon(s) here: [Optional]**
converted the ico to png: ![ddns-updater](https://user-images.githubusercontent.com/30209689/155371115-646152de-3548-45cf-8351-1fbc01c48990.png)
![sshwifty](https://user-images.githubusercontent.com/30209689/155370790-deddaa8c-4a42-4758-b85d-4f2eb7602b93.svg)
![lidarr](https://user-images.githubusercontent.com/30209689/155370599-301346c7-18fb-400d-944d-7722dcc7eefc.png)

**Comment by walkxcode** [comment]
Icons have been added.
