### ISSUE TITLE
[Icon Request]: 

### ISSUE THREAD

**Issue by xMAC94x** [walkxhub/dashboard-icons#53]
**What is the name of the icon(s)?**
Tandoor

**What is the website/page of the icon(s)?**
https://github.com/TandoorRecipes/recipes
https://tandoor.dev/

**Upload the icon(s) here: [Optional]**
https://github.com/vabene1111/recipes/raw/develop/docs/logo_color.svg

**Comment by walkxcode** [comment]
Tandoor was already added as an icon, but I've added the SVG.

**Comment by walkxcode** [comment]
Icon has been added.
