### ISSUE TITLE
[Icon Request]: zwavejs2mqtt

### ISSUE THREAD

**Issue by zackbcom** [walkxhub/dashboard-icons#58]
**What is the name of the icon(s)?**
zwavejs2mqtt

**What is the website/page of the icon(s)?**
https://zwave-js.github.io/zwavejs2mqtt/#/

**Upload the icon(s) here: [Optional]**
Upload the icon, MUST be `PNG` or `SVG`.
https://github.com/zwave-js/zwavejs2mqtt/blob/master/static/logo.png

**Comment by walkxcode** [comment]
Hey,
Thanks for suggesting an icon! Your icon(s) have been added to the repo. 🤍
