### ISSUE TITLE
[Icon Request]: babybuddy

### ISSUE THREAD

**Issue by zackbcom** [walkxhub/dashboard-icons#59]
**What is the name of the icon(s)?**
babybuddy

**What is the website/page of the icon(s)?**
https://github.com/babybuddy/babybuddy

**Upload the icon(s) here: [Optional]**
https://github.com/babybuddy/babybuddy/blob/master/babybuddy/static_src/logo/icon.png

**Comment by walkxcode** [comment]
Hey,
Thanks for suggesting an icon! Your icon(s) have been added to the repo. 🤍
