### ISSUE TITLE
[Icon Request]: dnla

### ISSUE THREAD

**Issue by espilioto** [walkxhub/dashboard-icons#63]
**What is the name of the icon(s)?**
dlna

**What is the website/page of the icon(s)?**
https://en.wikipedia.org/wiki/Digital_Living_Network_Alliance
(pretty much dead, but still quite popular)

**Upload the icon(s) here: [Optional]**
![dlna](https://user-images.githubusercontent.com/8510006/159135018-bb984791-5930-4a23-bf00-3fc8d3e66a5c.png)

**Comment by walkxcode** [comment]
Hey,
Thanks for suggesting an icon! Your icon(s) have been added to the repo. 🤍
