### ISSUE TITLE
[Icon Request]: Kavita 

### ISSUE THREAD

**Issue by jrhbcn** [walkxhub/dashboard-icons#68]
**What is the name of the icon(s)?**
Kavita Reader

**What is the website/page of the icon(s)?**
https://www.kavitareader.com/

**Upload the icon(s) here:**
PNG:
![logo](https://user-images.githubusercontent.com/22198270/160448375-6b278b9d-1e02-44a9-bf8e-576d006ae55d.png)
SVG:
![kavita](https://user-images.githubusercontent.com/22198270/160448402-0f7b8536-0b16-4733-81eb-76d178a8c9a7.svg)

**Comment by walkxcode** [comment]
Hey,
Thanks for suggesting an icon! Your icon(s) have been added to the repo. 🤍
