### ISSUE TITLE
[Icon Request]: AudioBookShelf

### ISSUE THREAD

**Issue by jrhbcn** [walkxhub/dashboard-icons#69]
**What is the name of the icon(s)?**
AudioBookShelf
**What is the website/page of the icon(s)?**
https://www.audiobookshelf.org/

**Upload the icon(s) here:**
PNG:
![logo](https://user-images.githubusercontent.com/22198270/160449160-f6469918-f412-4745-a393-a82eed3f374d.png)
SVG:
![audiobookshelf](https://user-images.githubusercontent.com/22198270/160450299-9c5fcc21-2626-47a4-8275-0e9016ef022e.svg)

**Comment by jrhbcn** [comment]
Is this one fine?
![audiobookshelf](https://user-images.githubusercontent.com/22198270/161075674-acdddfa0-348d-429e-bc1c-3f4e10abde5e.svg)

**Comment by jrhbcn** [comment]
Authors provide this:
![banner](https://user-images.githubusercontent.com/22198270/161091098-26eed551-a3b3-4bee-8567-34bbcb7a6c50.svg)

I just opened it in Inkscape and cropped the icon. Don't know why it does not work properly.

**Comment by walkxcode** [comment]
Hello,

Sorry for the delay. I've added the SVG after editing it manually.
