### ISSUE TITLE
[Icon Request]: Baserow

### ISSUE THREAD

**Issue by KucharczykL** [walkxhub/dashboard-icons#70]
**What is the name of the icon(s)?**
Baserow

**What is the website/page of the icon(s)?**
https://baserow.io/

**Upload the icon(s) here: [Optional]**
![baserow](https://user-images.githubusercontent.com/31072879/162192061-38a7a1d4-6fa5-4931-8268-90a73445f411.svg)

Unfortunately the icon on their website (that I have uploaded here) includes the name as well.

**Comment by KucharczykL** [comment]
Tried to crop it, not sure if the result is good but here you go :) 

![baserow](https://user-images.githubusercontent.com/31072879/162192898-8f37555e-39d0-47a4-84c4-26e73e6c34f0.svg)

**Comment by walkxcode** [comment]
Hey,
Thanks for suggesting an icon! Your icon(s) have been added to the repo. 🤍
