### ISSUE TITLE
![Icon Request]: DomainMod

### ISSUE THREAD

**Issue by N4v41** [walkxhub/dashboard-icons#71]
**What is the name of the icon(s)?**
DomainMod

**What is the website/page of the icon(s)?**
https://domainmod.org/

**Upload the icon(s) here: [Optional]**
Upload the icon, MUST be `PNG` or `SVG`.

**Comment by walkxcode** [comment]
I sadly can't find an image of high enough resolution to be or be made into an icon. If you have one, please send it.

**Comment by N4v41** [comment]
hi, found this in their support page:
![domainmod](https://user-images.githubusercontent.com/45365461/163525075-342fec01-468d-445c-826a-65e89614cc54.png)

**Comment by walkxcode** [comment]
> hi, found this in their support page:
> ![domainmod](https://user-images.githubusercontent.com/45365461/163525075-342fec01-468d-445c-826a-65e89614cc54.png)
> 
>  

Hello, this image isn't transparent nor high quality.

**Comment by N4v41** [comment]
![domainmodREFACTOR](https://user-images.githubusercontent.com/45365461/164882612-48c9db60-6bb7-4705-aef0-3d8992f7bc37.png)
made some changes to image and tried to enhance resolution by editing

**Comment by N4v41** [comment]
@walkxcode  what do you think ? is it good enough?

> ![domainmodREFACTOR](https://user-images.githubusercontent.com/45365461/164882612-48c9db60-6bb7-4705-aef0-3d8992f7bc37.png) made some changes to image and tried to enhance resolution by editing

**Comment by walkxcode** [comment]
Sorry for the late reply! LGTM!

**Comment by walkxcode** [comment]
Hey,
Thanks for suggesting an icon! Your icon(s) have been added to the repo. 🤍
