### ISSUE TITLE
[Icon Request]: Authentik

### ISSUE THREAD

**Issue by DrMxrcy** [walkxhub/dashboard-icons#73]
**What is the name of the icon(s)?**
Authentik

**What is the website/page of the icon(s)?**
https://goauthentik.io/

**Upload the icon(s) here: [Optional]**
[Icon Link](https://d33wubrfki0l68.cloudfront.net/3986a9ebfee622cb3fed7c0b7d3661e431dcff5c/8fd41/img/icon_top_brand.svg)

**Comment by walkxcode** [comment]
Hello, icons for authentik are already in the repo. 
https://github.com/walkxhub/dashboard-icons/blob/master/png/authentik.png
https://github.com/walkxhub/dashboard-icons/blob/master/svg/authentik.svg
