### ISSUE TITLE
[Icon Request]: NocoDB

### ISSUE THREAD

**Issue by DrMxrcy** [walkxhub/dashboard-icons#74]
**What is the name of the icon(s)?**
NocoDB
**What is the website/page of the icon(s)?**
[NocoDB Link](https://nocodb.com/)

**Upload the icon(s) here: [Optional]**
Upload the icon, MUST be `PNG` or `SVG`.
[Link to PNG](https://nocodb.com/brand/x1.png)

**Comment by walkxcode** [comment]
Hey,
Thanks for suggesting an icon! Your icon(s) have been added to the repo. 🤍
