### ISSUE TITLE
[Icon Request]: Private Internet Access

### ISSUE THREAD

**Issue by MayhemBill** [walkxhub/dashboard-icons#79]
**What is the name of the icon(s)?**
[Eg. Portainer] privateinternetaccess

**What is the website/page of the icon(s)?**
[Eg. https://portainer.io] https://privateinternetaccess.com

**Upload the icon(s) here: [Optional]**
Upload the icon, MUST be `PNG` or `SVG`. 
![privateinternetaccess](https://user-images.githubusercontent.com/5598969/164952308-1a6d85ed-6300-4ef9-a17b-bfd0614c7569.png)

**Comment by walkxcode** [comment]
Hey, this doesn't seem to be the official icon. I will go ahead and add the official one though.
![private-internet-access](https://user-images.githubusercontent.com/71191962/165363857-23b57614-cc68-42aa-b403-a089223385b8.png)

**Comment by walkxcode** [comment]
Hey,
Thanks for suggesting an icon! Your icon(s) have been added to the repo. 🤍
