### ISSUE TITLE
[Icon Request]: Falcon Player (Pi) - FPP

### ISSUE THREAD

**Issue by bmcgonag** [walkxhub/dashboard-icons#81]
**What is the name of the icon(s)?**
Falcon Player Pi

**What is the website/page of the icon(s)?**
https://github.com/FalconChristmas/fpp)](https://github.com/FalconChristmas/fpp

**Upload the icon(s) here: [Optional]**
Upload the i
![falcon-player](https://user-images.githubusercontent.com/7346620/165868055-0db3e181-a288-42da-88b5-debbca3365eb.svg)
![falcon-player](https://user-images.githubusercontent.com/7346620/165868057-79f23fef-86eb-41b3-b3a3-13772725258c.png)
con, MUST be `PNG` or `SVG`.

**Comment by bmcgonag** [comment]
I think the icons are white, so not showing up in day mode...

**Comment by walkxcode** [comment]
Why don't we just use the official logo? This will show up in both Light and Dark mode. 
![image](https://user-images.githubusercontent.com/71191962/165928603-ffa88b8e-5def-4499-acc5-7c196a0b570c.png)

**Comment by walkxcode** [comment]
Also, Hello Brian! Didn't notice it was you at first 🙂

**Comment by bmcgonag** [comment]
Yep, that works for me.

**Comment by walkxcode** [comment]
Hey,
Thanks for suggesting an icon! Your icon(s) have been added to the repo. 🤍
