### ISSUE TITLE
[Icon Request]: RPort

### ISSUE THREAD

**Issue by bmcgonag** [walkxhub/dashboard-icons#82]
**What is the name of the icon(s)?**
RPort

**What is the website/page of the icon(s)?**
[https://rport.io](https://rport.io/)

**Upload the icon(s) here: [Optional]**
Upload the icon, MUST be `PNG` or `SVG`.
![rport-img](https://user-images.githubusercontent.com/7346620/166240599-46e34896-2c4d-44e7-99c0-b32309e1303b.png)
![rport-img](https://user-images.githubusercontent.com/7346620/166240602-612651b2-b504-4d0a-aba8-90e39715cb41.svg)

**Comment by walkxcode** [comment]
Hey,
Thanks for suggesting an icon! Your icon(s) have been added to the repo. 🤍
