### ISSUE TITLE
[Icon Request]: Metabase

### ISSUE THREAD

**Issue by bmcgonag** [walkxhub/dashboard-icons#84]
**What is the name of the icon(s)?**
[Eg. Portainer]
Metabase

**What is the website/page of the icon(s)?**
[Eg. https://portainer.io]
https://www.metabase.com/
![metabase](https://user-images.githubusercontent.com/7346620/167405773-403e6cb6-bb57-41bb-8514-e6a371fbb8cd.png)

**Upload the icon(s) here: [Optional]**
Upload the icon, MUST be `PNG` or `SVG`.

**Comment by walkxcode** [comment]
Hey,
Thanks for suggesting an icon! Your icon(s) have been added to the repo. 🤍
