### ISSUE TITLE
[Icon Request]: Quant UX

### ISSUE THREAD

**Issue by bmcgonag** [walkxhub/dashboard-icons#85]
**What is the name of the icon(s)?**
[Eg. Portainer]
Quant UX
**What is the website/page of the icon(s)?**
[Eg. https://portainer.io]
https://quant-ux.com

**Upload the icon(s) here: [Optional]**
Upload the icon, MUST be `PNG` or `SVG`.
![quant-ux](https://user-images.githubusercontent.com/7346620/167407244-eb3b1e76-29ce-4192-b5f7-6d8e66aa7210.png)

**Comment by walkxcode** [comment]
Hey,
Thanks for suggesting an icon! Your icon(s) have been added to the repo. 🤍
