### ISSUE TITLE
[Icon Request]: iSpy Agent DVR

### ISSUE THREAD

**Issue by bmcgonag** [walkxhub/dashboard-icons#87]
**What is the name of the icon(s)?**
[Eg. Portainer]
ipy-agent-dvr

**What is the website/page of the icon(s)?**
[Eg. https://portainer.io]
https://www.ispyconnect.com/

**Upload the icon(s) here: [Optional]**
Upload the icon, MUST be `PNG` or `SVG`.
![ispy-agent-dvr](https://user-images.githubusercontent.com/7346620/167408134-844910e3-571e-41ca-8fd5-f827f2fbfc35.png)

**Comment by walkxcode** [comment]
Hey,
Thanks for suggesting an icon! Your icon(s) have been added to the repo. 🤍
