### ISSUE TITLE
[Icon Request]: Netmaker

### ISSUE THREAD

**Issue by bmcgonag** [walkxhub/dashboard-icons#88]
**What is the name of the icon(s)?**
[Eg. Portainer]
netmaker

**What is the website/page of the icon(s)?**
[Eg. https://portainer.io]
https://www.netmaker.org/

**Upload the icon(s) here: [Optional]**
Upload the icon, MUST be `PNG` or `SVG`.
![netmaker](https://user-images.githubusercontent.com/7346620/167408488-1ffed562-533f-4ab1-99fb-84205b6e531e.png)

**Comment by walkxcode** [comment]
Hey,
Thanks for suggesting an icon! Your icon(s) have been added to the repo. 🤍
