### ISSUE TITLE
[Icon Request]: arris logo

### ISSUE THREAD

**Issue by rscm** [walkxhub/dashboard-icons#90]
**What is the name of the icon(s)?**
arris

**What is the website/page of the icon(s)?**
https://www.surfboard.com/

**Upload the icon(s) here: [Optional]**
![arris-logo](https://user-images.githubusercontent.com/6588120/168186527-193561ec-6e46-4561-a3ae-edbab45974ca.png)

**Comment by walkxcode** [comment]
Hey,
Thanks for suggesting an icon! Your icon(s) have been added to the repo. 🤍
