### ISSUE TITLE
[Icon Request]: FileBot

### ISSUE THREAD

**Issue by mau671** [walkxhub/dashboard-icons#95]
**What is the name of the icon(s)?**
FileBot

**What is the website/page of the icon(s)?**
https://www.filebot.net/

**Upload the icon(s) here: [Optional]**
PNG:
![filebot](https://user-images.githubusercontent.com/78320202/169625626-b000587f-c0f3-486a-841a-978e4d8c0315.png)

SVG:
![filebot](https://user-images.githubusercontent.com/78320202/169625639-f1a325b0-8239-414c-98cd-c76ce7632ea4.svg)

**Comment by walkxcode** [comment]
Hey,
Thanks for suggesting an icon! Your icon(s) have been added to the repo. 🤍
